**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np


###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [21]:
#Code here
a=np.nan * np.empty(10)
a[4]=1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [6]:
#Code here
a=int(input("Enter the number a"))
b=int(input("Enter the number b"))
c=np.random.random((a,b))
print(c)
print(np.mean(c))

Enter the number a2
Enter the number b3
[[0.30833536 0.55171465 0.90544389]
 [0.34495893 0.35076047 0.59094393]]
0.5086928717639222


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [27]:
#Code here
def borderarray(a,b):
    a=np.ones((a,b))
    a[1:-1,1:-1]=0
    return a
borderarray(4,5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [32]:
#Code here
a=np.linspace(0,1,12)
a[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here
No

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [35]:
#Code here
z=np.zeros((5,5))
z+=np.arange(0,5)
z

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [43]:
#code here
x=np.random.randint(1,100,(10,2))
y=np.array([2,3])
np.sqrt(np.sum((x-y)**2, axis=1)).astype(int)

array([ 97,  87,  78,  54,  17,  90,  85,  53, 105,  38])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [44]:
#Code here
np.unravel_index(100,(6,7,8))

(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [45]:
#Code here
x=np.array([1 ,2, 3, 4, -8, -10])
x[::-1].astype(float)

array([-10.,  -8.,   4.,   3.,   2.,   1.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [48]:
#Code here
a=np.array([1, 2,3,4])
a.size

4

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [51]:
#Code here
def softmax(array):
  if type(array)!=np.ndarray:
    raise TypeError("Requires Numpy array")
  elif np.ndim(array)>1:
    raise TypeError("Requires 1D array")
  s=np.sum(np.exp(array))
  return np.exp(array)/s
x=np.array([33.17344305, 45.61961654, 82.05405781, 80.9647098  ,68.82830233 ,91.52064278])
softmax(x)

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [54]:
#Code here
def vstack(*args):
  for i in args:
    if type(i)!=np.ndarray:
      raise TypeError("Requires Numpy Array")
  return np.vstack(args)

a = np.arange(10).reshape(2, -1)
print("a=",a)
b = np.repeat(1, 10).reshape(2, -1)
print("b=",b)
print(vstack(a,b))
c = np.random.random((2,5))
print("c=", c)
vstack(a,b,c)

a= [[0 1 2 3 4]
 [5 6 7 8 9]]
b= [[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
c= [[0.38325505 0.05770041 0.22669281 0.43451135 0.01388666]
 [0.91895192 0.61039245 0.31364802 0.2100718  0.57950418]]


array([[0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.        , 6.        , 7.        , 8.        , 9.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.38325505, 0.05770041, 0.22669281, 0.43451135, 0.01388666],
       [0.91895192, 0.61039245, 0.31364802, 0.2100718 , 0.57950418]])

###`Q-14:` Subtract the mean of each row from a matrix.

In [55]:
#code here
x=np.random.random((5,4))
x-x.mean(axis=1,keepdims=True)

array([[ 0.38614095, -0.40231468,  0.19525342, -0.17907969],
       [ 0.36665906, -0.26209613,  0.1783964 , -0.28295933],
       [ 0.04033803,  0.21589902, -0.48314665,  0.22690961],
       [-0.03020395, -0.23418755,  0.21683898,  0.04755252],
       [-0.03645656, -0.30712395, -0.170949  ,  0.5145295 ]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [57]:
#Code here
x=np.arange(9).reshape(3,3)
x[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

###`Q-16:` Replace odd elements in arrays with -1.

In [60]:
#Code here
x=np.arange(10)

x[x%2==1]=-1
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [63]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
import numpy as np

# Given arrays
a = np.array([6, 3, 1, 5, 8])
b = np.array([3, 2, 1, 7, 2])

# Element-wise maximum
result = np.maximum(a, b)

print("Array a:", a)
print("Array b:", b)
print("Element-wise maximum:", result)


Array a: [6 3 1 5 8]
Array b: [3 2 1 7 2]
Element-wise maximum: [6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [65]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[8871, 1536, 5092, 8988, 3742],
       [1811, 7745, 7978, 1639, 6775],
       [8067,  194, 7575, 3275, 6395],
       [ 158, 9421, 5067,  501, 3380],
       [2639, 7218, 2900,  810, 8852],
       [1716, 1942, 3948, 9712, 8042],
       [7731, 9222, 4840, 6957, 1759],
       [1156, 4060, 5846, 9701, 1251]])

In [66]:
#Code here
arr1[:,::2]

array([[8871, 5092, 3742],
       [1811, 7978, 6775],
       [8067, 7575, 6395],
       [ 158, 5067, 3380],
       [2639, 2900, 8852],
       [1716, 3948, 8042],
       [7731, 4840, 1759],
       [1156, 5846, 1251]])

In [67]:
(arr1-arr1.min())/(arr1.max()-arr1.min())

array([[0.91197404, 0.14423278, 0.51643291, 0.92422022, 0.37513084],
       [0.17301654, 0.79411765, 0.81850534, 0.15501361, 0.69258949],
       [0.82782081, 0.00376806, 0.77632405, 0.32625079, 0.65281557],
       [0.        , 0.96954155, 0.5138162 , 0.03590119, 0.33724095],
       [0.25968181, 0.7389575 , 0.28700021, 0.06824367, 0.90998535],
       [0.16307306, 0.18672807, 0.39669248, 1.        , 0.8252041 ],
       [0.79265229, 0.94871258, 0.49005652, 0.7116391 , 0.16757379],
       [0.10445887, 0.40841532, 0.59535273, 0.99884865, 0.11440234]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [68]:
#Code here
def nthmax(arr, n):
    if n>len(arr):
        raise IndexError("n is way out of limit")
    arr.sort()
    return arr[-n]
nthmax(np.array([12,34,40,7,1,0]),2)

34

In [74]:
a=np.array([12,34,40,7,1,0])
np.sort(a)

array([ 0,  1,  7, 12, 34, 40])

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [3]:
#code here
a = np.array([1,2,3])
np.hstack([np.repeat(a, 3), np.tile(a, 3)])

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])